-- ============================================================
-- PVP99 - BANUTA TASK - MANIFEST
-- Gerado para o BOT MANAGER.
-- ============================================================

return {
  name = "BANUTA TASK",
  version = "1.0",

  directories = {
    "cavebot",
    "cavebot_configs",
    "storage",
    "targetbot",
    "targetbot_configs",
    "vBot",
    "vBot_configs",
    "vBot_configs/profile_1",
    "vBot_configs/profile_10",
    "vBot_configs/profile_2",
    "vBot_configs/profile_3",
    "vBot_configs/profile_4",
    "vBot_configs/profile_5",
    "vBot_configs/profile_6",
    "vBot_configs/profile_7",
    "vBot_configs/profile_8",
    "vBot_configs/profile_9",
  },

  files = {
    "_Loader.lua",
    "cavebot/actions.lua",
    "cavebot/bank.lua",
    "cavebot/buy_supplies.lua",
    "cavebot/cavebot.lua",
    "cavebot/cavebot.otui",
    "cavebot/clear_tile.lua",
    "cavebot/config.lua",
    "cavebot/config.otui",
    "cavebot/d_withdraw.lua",
    "cavebot/depositor.lua",
    "cavebot/doors.lua",
    "cavebot/editor.lua",
    "cavebot/editor.otui",
    "cavebot/example_functions.lua",
    "cavebot/extension_template.lua",
    "cavebot/imbuing.lua",
    "cavebot/inbox_withdraw.lua",
    "cavebot/lure.lua",
    "cavebot/minimap.lua",
    "cavebot/pos_check.lua",
    "cavebot/recorder.lua",
    "cavebot/sell_all.lua",
    "cavebot/stand_lure.lua",
    "cavebot/supply_check.lua",
    "cavebot/tasker.lua",
    "cavebot/travel.lua",
    "cavebot/walking.lua",
    "cavebot/withdraw.lua",
    "cavebot_configs/1 andar.cfg",
    "cavebot_configs/2 andar.cfg",
    "storage/profile_1.json",
    "targetbot/creature.lua",
    "targetbot/creature_attack.lua",
    "targetbot/creature_editor.lua",
    "targetbot/creature_editor.otui",
    "targetbot/creature_priority.lua",
    "targetbot/looting.lua",
    "targetbot/looting.otui",
    "targetbot/target.lua",
    "targetbot/target.otui",
    "targetbot/walking.lua",
    "targetbot_configs/Banuta.json",
    "vBot/alarms.lua",
    "vBot/alarms.otui",
    "vBot/analyzer.lua",
    "vBot/analyzer.otui",
    "vBot/antiRs.lua",
    "vBot/AttackBot.lua",
    "vBot/AttackBot.otui",
    "vBot/BotServer.lua",
    "vBot/BotServer.otui",
    "vBot/cast_food.lua",
    "vBot/cavebot.lua",
    "vBot/cavebot_control_panel.lua",
    "vBot/combo.lua",
    "vBot/combo.otui",
    "vBot/Conditions.lua",
    "vBot/Conditions.otui",
    "vBot/configs.lua",
    "vBot/Containers.lua",
    "vBot/depositer_config.lua",
    "vBot/depositer_config.otui",
    "vBot/depot_withdraw.lua",
    "vBot/Dropper.lua",
    "vBot/eat_food.lua",
    "vBot/equip.lua",
    "vBot/Equipper.lua",
    "vBot/equipper.otui",
    "vBot/exeta.lua",
    "vBot/extras.lua",
    "vBot/extras.otui",
    "vBot/HealBot.lua",
    "vBot/HealBot.otui",
    "vBot/hold_target.lua",
    "vBot/ingame_editor.lua",
    "vBot/items.lua",
    "vBot/main.lua",
    "vBot/new_cavebot_lib.lua",
    "vBot/new_healer.lua",
    "vBot/new_healer.otui",
    "vBot/npc_talk.lua",
    "vBot/playerlist.lua",
    "vBot/playerlist.otui",
    "vBot/pushmax.lua",
    "vBot/pushmax.otui",
    "vBot/quiver_label.lua",
    "vBot/quiver_manager.lua",
    "vBot/Sio.lua",
    "vBot/siolist.otui",
    "vBot/spy_level.lua",
    "vBot/supplies.lua",
    "vBot/supplies.otui",
    "vBot/tools.lua",
    "vBot/version.txt",
    "vBot/vlib.lua",
    "vBot/xeno_menu.lua",
    "vBot_configs/profile_1/AttackBot.json",
    "vBot_configs/profile_1/HealBot.json",
    "vBot_configs/profile_1/Supplies.json",
  }
}
